// <auto-generated />
using System;
using InstrumentPlatform.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InstrumentPlatform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316204635_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InstrumentPlatform.Entities.InstrumentEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_name");

                    b.Property<int>("InstrumentState")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comport");

                    b.Property<string>("SoftwareVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("software_version");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("DeviceId");

                    b.ToTable("instruments");
                });

            modelBuilder.Entity("InstrumentPlatform.Entities.MeasurementEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deviceId");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measuredAt");

                    b.Property<float>("Value")
                        .HasColumnType("real")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("measurements");
                });

            modelBuilder.Entity("InstrumentPlatform.Entities.MeasurementEntity", b =>
                {
                    b.HasOne("InstrumentPlatform.Entities.InstrumentEntity", "Instument")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instument");
                });
#pragma warning restore 612, 618
        }
    }
}
