// <auto-generated />
using System;
using InstrumentPlatform.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InstrumentPlatform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417093643_RenameColumns")]
    partial class RenameColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InstrumentPlatform.Entities.AuthorizedInstrument", b =>
                {
                    b.Property<string>("InstrumentId")
                        .HasColumnType("text")
                        .HasColumnName("instrument_id");

                    b.HasKey("InstrumentId");

                    b.ToTable("authorized");

                    b.HasData(
                        new
                        {
                            InstrumentId = "TC-00000"
                        },
                        new
                        {
                            InstrumentId = "H2-00000"
                        });
                });

            modelBuilder.Entity("InstrumentPlatform.Entities.InstrumentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("port");

                    b.Property<string>("SoftwareVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("software_version");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.ToTable("instruments");
                });

            modelBuilder.Entity("InstrumentPlatform.Entities.MeasurementEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instrument_id");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at");

                    b.Property<float>("Value")
                        .HasColumnType("real")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.ToTable("measurements");
                });

            modelBuilder.Entity("InstrumentPlatform.Entities.InstrumentEntity", b =>
                {
                    b.HasOne("InstrumentPlatform.Entities.AuthorizedInstrument", null)
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InstrumentPlatform.Entities.MeasurementEntity", b =>
                {
                    b.HasOne("InstrumentPlatform.Entities.InstrumentEntity", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });
#pragma warning restore 612, 618
        }
    }
}
